In [2]:
import pandas as pd
import numpy as np

In [5]:
# dataframe

info = {
    "name": ["abhi", "arya", "aditi"],
    "age" : [24,20,23],
    "gpa" : [9.3, 8.2, 9.8]
}

df = pd.DataFrame(info)

print(df, type(df))

    name  age  gpa
0   abhi   24  9.3
1   arya   20  8.2
2  aditi   23  9.8 <class 'pandas.DataFrame'>

In [6]:
df

    name  age  gpa
0   abhi   24  9.3
1   arya   20  8.2
2  aditi   23  9.8

In [9]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'gpa'], dtype='str')

In [10]:
# dataframe from list

df = pd.DataFrame([["abhi", 24],["aditi", 23],["preeti", 25]], columns=["Name", "Age"])
df

     Name  Age
0    abhi   24
1   aditi   23
2  preeti   25

In [11]:
# dataframe from numpy array
np_arr = np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(np_arr, columns=["A", "B", "C"])

df

   A  B  C
0  1  2  3
1  4  5  6

In [14]:
df = pd.read_csv("employee_data.csv")

print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [16]:
print(df.head()) # starting 5 rows data print

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [17]:
print(df.head(3)) # specifie custom rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000

In [18]:
df.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [19]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [21]:
df.sample()

   ID     Name  Age Department  Salary
2   3  Charlie   28    Finance   48000

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

In [23]:
df.shape

(10, 5)

In [24]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

In [25]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [27]:

df = pd.read_csv("globalAirQuality.csv")

df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  str
 1   country      18000 non-null  str
 2   city         18000 non-null  str
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), str(3)
memory usage: 2.1 MB

In [37]:
# selecting data

# df["city"]
df[["city", "aqi"]].head()

       city  aqi
0  New York  108
1  New York   90
2  New York   84
3  New York  158
4  New York   97